export const RECIPE_INSERT = 'RECIPE_INSERT';
export const RECIPE_GET = 'RECIPE_GET';

export const POPUP_RECIPE_INGREDIENT_UPDATE = 'POPUP_RECIPE_INGREDIENT/UPDATE';
export const POPUP_RECIPE_INSTRUCTIONS_UPDATE =
  'POPUP_RECIPE_INSTRUCTIONS_UPDATE';
export const POPUP_RECIPE_TITLE_UPDATE = 'POPUP_RECIPE_TITLE_UPDATE';
export const POPUP_CLEAN_STATE = 'POPUP_CLEAN_STATE';

export const RECIPE_ACTIVEID_SWITCH = 'RECIPE_ACTIVEID_SWITCH';
