// Recipe disply
export const RECIPE_GET = 'RECIPE_GET';
export const RECIPE_ACTIVEID_SWITCH = 'RECIPE_ACTIVEID_SWITCH';
export const RECIPE_UPDATE = 'RECIPE_UPDATE';
export const RECIPE_DELETE = 'RECIPE_DELETE';

// Add new recipe
export const RECIPE_INSERT = 'RECIPE_INSERT';
export const POPUP_RECIPE_INGREDIENT_UPDATE = 'POPUP_RECIPE_INGREDIENT_UPDATE';
export const POPUP_RECIPE_INSTRUCTIONS_UPDATE =
  'POPUP_RECIPE_INSTRUCTIONS_UPDATE';
export const POPUP_RECIPE_TITLE_UPDATE = 'POPUP_RECIPE_TITLE_UPDATE';
export const POPUP_CLEAN_STATE = 'POPUP_CLEAN_STATE';

// Edit recipe
export const EDIT_RECIPE_INSERT = 'EDIT_RECIPE_INSERT';
export const EDIT_RECIPE_INGREDIENTS_UPDATE = 'EDIT_RECIPE_INGREDIENTS_UPDATE';
export const EDIT_RECIPE_INSTRUCTIONS_UPDATE =
  'EDIT_RECIPE_INSTRUCTIONS_UPDATE';
export const EDIT_RECIPE_TITLE_UPDATE = 'EDIT_RECIPE_TITLE_UPDATE';
export const EDIT_CLEAN_STATE = 'EDIT_CLEAN_STATE';
